services:
  app:
    image: ubuntu:22.04
    volumes:
      - ./dev:/opt/app
      - ./dev/templates:/opt/app/templates
      - ./dev/build:/opt/app/build
    working_dir: /opt/app
    environment:
      PYTHONUNBUFFERED: 1
      PYTHONDONTWRITEBYTECODE: 1
volumes:
  app:
    external: true

# include:
#   - infra.yaml
# services:
#   web:
#     build: .
#     ports:
#       - "8000:5000"
#     develop:
#       watch:
#         - action: sync
#           path: .
#           target: /code
# services:  
#   redis:
#     image: "redis:alpine"